#!/usr/bin/env node
// Regenerates the two shared index files from each sketch's own metadata:
//
//   sketches/<slug>/sketch.json  ->  sketches.data.js (gallery manifest)
//                                ->  README.md table (between the markers)
//
// Sketch branches only ever add/edit their own sketch.json, so parallel
// branches never conflict on these shared files. CI (.github/workflows/
// pages.yml) runs this on every push to main and commits the result.
//
// Usage: node tools/build-index.js [--check]
//   --check  exit 1 if the generated files are out of date (no writes)
"use strict";
const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "..");
const sketchesDir = path.join(root, "sketches");
const STATUSES = ["seed", "prototype", "active", "archived", "graduated"];
// Statuses that close a sketch (see "Closing a sketch" in CLAUDE.md).
const CLOSED = ["archived", "graduated"];
const START = "<!-- sketches:start (generated by tools/build-index.js; edit sketches/<slug>/sketch.json instead) -->";
const END = "<!-- sketches:end -->";

function load() {
  const out = [];
  for (const slug of fs.readdirSync(sketchesDir).sort()) {
    const file = path.join(sketchesDir, slug, "sketch.json");
    if (!fs.existsSync(file)) continue;
    let meta;
    try {
      meta = JSON.parse(fs.readFileSync(file, "utf8"));
    } catch (e) {
      throw new Error(`${path.relative(root, file)}: ${e.message}`);
    }
    for (const k of ["title", "description", "date", "status"]) {
      if (!meta[k]) throw new Error(`${path.relative(root, file)}: missing "${k}"`);
    }
    if (!STATUSES.includes(meta.status)) {
      throw new Error(`${path.relative(root, file)}: status must be one of ${STATUSES.join(", ")}`);
    }
    const where = path.relative(root, file);
    if (meta.closed !== undefined && !/^\d{4}-\d{2}-\d{2}$/.test(meta.closed)) throw new Error(`${where}: "closed" must be a YYYY-MM-DD date`);
    if (meta.outcome !== undefined && typeof meta.outcome !== "string") throw new Error(`${where}: "outcome" must be a string`);
    if (meta.successor !== undefined && (!meta.successor || typeof meta.successor.title !== "string")) {
      throw new Error(`${where}: "successor" needs at least a "title"`);
    }
    if (CLOSED.includes(meta.status) && !meta.closed) throw new Error(`${where}: a ${meta.status} sketch needs a "closed" date`);
    if (meta.status === "graduated" && !meta.successor) throw new Error(`${where}: a graduated sketch needs a "successor"`);
    out.push({ slug, ...meta });
  }
  // Oldest first; slug breaks ties so the order is deterministic.
  return out.sort((a, b) => a.date.localeCompare(b.date) || a.slug.localeCompare(b.slug));
}

function manifest(sketches) {
  const entries = sketches.map((s) => {
    const entry = {
      slug: s.slug,
      title: s.title,
      description: s.description,
      date: s.date,
      status: s.status,
      tags: s.tags || [],
      demo: s.demo ? `sketches/${s.slug}/${s.demo}` : null,
    };
    if (s.closed) entry.closed = s.closed;
    if (s.outcome) entry.outcome = s.outcome;
    if (s.successor) entry.successor = { title: s.successor.title, repo: s.successor.repo || null, url: s.successor.url || null };
    const body = Object.entries(entry)
      .map(([k, v]) => `    ${k}: ${JSON.stringify(v)},`)
      .join("\n");
    return `  {\n${body}\n  },`;
  });
  return `// GENERATED by tools/build-index.js from sketches/<slug>/sketch.json.
// Don't edit by hand, and don't commit changes to it from a sketch branch.
// CI regenerates it on every push to main, which keeps parallel sketch
// branches from conflicting here.
//
// Plain JS (not JSON) loaded via a classic <script> tag on purpose:
// fetch()/XHR for local files is blocked by browsers under file:// (no
// server), and the gallery needs to work from a straight double-click.
window.SKETCHES = [
${entries.join("\n")}
];
`;
}

function cell(s) { return String(s).replace(/\|/g, "\\|").replace(/\n/g, " "); }

function table(sketches) {
  const rows = sketches.map((s) => {
    const demo = s.demo ? `[Live](sketches/${s.slug}/${s.demo})` : "—";
    const next = s.successor ? (s.successor.url ? ` → [${cell(s.successor.title)}](${s.successor.url})` : ` → ${cell(s.successor.title)}`) : "";
    return `| [${s.slug}](sketches/${s.slug}/) | ${cell(s.summary || s.description)} | ${s.status}${next} | ${demo} |`;
  });
  return [START, "| Sketch | Description | Status | Demo |", "| --- | --- | --- | --- |", ...rows, END].join("\n");
}

function main() {
  const check = process.argv.includes("--check");
  const sketches = load();

  const dataPath = path.join(root, "sketches.data.js");
  const readmePath = path.join(root, "README.md");
  const readme = fs.readFileSync(readmePath, "utf8");
  const i = readme.indexOf(START), j = readme.indexOf(END);
  if (i < 0 || j < i) throw new Error("README.md: sketches table markers not found");

  const next = {
    [dataPath]: manifest(sketches),
    [readmePath]: readme.slice(0, i) + table(sketches) + readme.slice(j + END.length),
  };
  let stale = false;
  for (const [file, content] of Object.entries(next)) {
    const current = fs.existsSync(file) ? fs.readFileSync(file, "utf8") : "";
    if (current === content) continue;
    stale = true;
    if (check) console.log(`out of date: ${path.relative(root, file)}`);
    else { fs.writeFileSync(file, content); console.log(`wrote ${path.relative(root, file)}`); }
  }
  if (!stale) console.log(`up to date (${sketches.length} sketches)`);
  if (check && stale) process.exit(1);
}

main();
